name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  NO_SUDO: 1
  #DAY_OF_WEEK: Monday
  

jobs:
  build_centos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["centos:7"]

    container:
      image: ${{ matrix.container }}
      
    steps:
    - name: checkout
      uses: actions/checkout@v3


    - name: intall deps
      run: |
        yum install -y wget tar gcc automake autoconf libtool make
        
    #- name: configure
    #  run: ./configure

    #- name: Install dependencies
    #  run: make

    #- name: Run check
    #  run: make check

    - name: Run distcheck
      id: rpm
      run: make USE_PROMETHEUS=1

    - name: check for new builds
      run: ls

    - name: 'Upload Package'
      uses: actions/upload-artifact@v1
      with:
        name: nuget
        path: ${{ github.workspace }}/../rpmbuild/RPMS/x86_64/*.x86_64.rpm
    
      
