name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_centos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["centos:7"]

    container:
      image: ${{ matrix.container }}
      
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: rpmbuild
      uses: robertdebock/rpmbuild-action@1.1.1

    - name: intall deps
      run: |
        yum install -y wget tar gcc automake autoconf libtool make
        
    #- name: configure
    #  run: ./configure

    #- name: Install dependencies
    #  run: make

    #- name: Run check
    #  run: make check

    - name: Run distcheck
      run: make USE_PROMETHEUS=1
