name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v3

    - name: intall deps
      run: |
        yum install -y wget tar gcc automake autoconf libtool make
        
    #- name: configure
    #  run: ./configure

    #- name: Install dependencies
    #  run: make

    #- name: Run check
    #  run: make check

    - name: Run distcheck
      run: make USE_PROMETHEUS=1
